### ISSUE TITLE
The app cannot run use the new settings

### ISSUE THREAD

**Issue by w9wen** [SeeedJP/ReButtonApp#2]
I walkthrough the guide [ReButton](https://github.com/SeeedJP/ReButton) to set up my ReButton, it worked.
But when I changed my Azure IoT Central to another domain (created a new Azure IoT Central), and it success when save this connect information to ReButton, but **the ReButton trigger event still send to the old Azure IoT Central**.

Notes:

My ReButtion firmware version is 2.0.

Thank you.

**Comment by matsujirushi** [comment]
Hi @w9wen ,
Please clear the IoT Hub settings when you change to connect other Azure IoT Central.

FYI
https://github.com/SeeedJP/ReButtonApp/blob/master/ReButtonClient.cpp#L106

**Comment by w9wen** [comment]
> Hi @w9wen ,
> Please clear the IoT Hub settings when you change to connect other Azure IoT Central.
> 
> FYI
> https://github.com/SeeedJP/ReButtonApp/blob/master/ReButtonClient.cpp#L106
Hello Takashi
It worked when I clear the Azure IoT Hub connection string, thanks'.
![2018-12-19 05 32 35](https://user-images.githubusercontent.com/6820684/50184703-c6421f80-0350-11e9-8320-d99d4ed7bc07.png)
